server:
    port: 8080

spring:
    datasource:
      url:  jdbc:postgresql://localhost:15432/apple_company
      username: farid
      password: 123456

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        hibernate:
          ddl-auto: create
